---
title: "p1_IntroR"
author: "Jilung Hsieh"
date: "2019/10/28"
output:
  html_document:
    highlight: zenburn
    theme: cerulean
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Installing following pagages
```{r}
# install.packages("tidyverse")
```


# Loading libraries and global options

```{r}
library(tidyverse)
options(stringsAsFactors = F)
```



# Loading data

```{r}
users <- read_csv("data_china_accounts/china_082019_1_users_csv_hashed.csv")
```



# Previewing data 觀察資料
- `glimpse()`
- `dim`
- `class`
- `View` and `head`

```{r}
glimpse(users)
users %>% glimpse()

dim(users)
users %>% dim


class(users)
users %>% class


# View(users)
# users %>% View 
# View(head(users))
# users %>% head %>% View
users %>% head 
```



# Selecting columns 選擇所要的變項欄
- `select()`

```{r}
selected <- select(users, userid, user_display_name, user_screen_name)
selected <- users %>% 
    select(userid, user_display_name, user_screen_name)
```


# Filter rows 篩選某變項符合條件的資料
- `filter()`

```{r}
users %>%
    filter(nchar(user_screen_name) > 20)
```

